PSDaily/Algorithm-Study

- 1339.cpp
- 13904.cpp
https://www.acmicpc.net/problem/13904
<br/>
> 과제 마감 날짜와 과제 점수가 주어지고, 하루에 과제 한개만 수행할 수 있을 때
웅찬이가 얻을 수 있는 과제 점수 최댓값을 구하는 문제!
<br/>
**첫번째 풀이**
점수 기준으로 내림차순 정렬해주고, 현재 날짜를 1씩 올려주면서 현재 날짜보다 마감 날짜가 큰 과제를 찾아 해당 과제의 점수를 sum에 더해주는 방식으로 풀었다.
이 풀이의 문제점은 아래 사진처럼 (4, 40) 보다 (3, 30)을 먼저 수행했다면 둘 다 과제 점수를 얻을 수 있었을텐데...과제 점수가 높은 (4, 40)부터 수행하여 (3, 30)의 점수를 얻지 못 하는 케이스가 나온다.
**-> 여기서 얻은 해결책 : 최대한 마감날짜와 가까운 날짜에 과제를 수행하면 된다!**
**두번째 풀이**
score 배열을 만들어서 **score[마감날짜] = 과제 점수**
이렇게 저장해줄건데 (이게 마감 날짜에 가장 가깝게 과제를 하는 최적의 경우임) 만약 이미 저장된 값이 있다면 마감 날짜 ~ 1일까지 순회하며 빈 공간에 과제 점수를 채워준다.
만약 빈 공간이 없다면? 이미 과제점수가 큰 과제들을 수행할 계획에 있는 거라서 현재 과제를 수행하지 않아도 된다!
<br/>
>  재밌는 문제다!
<br/>
> [0319] 13904번 - 과제

- .idea/.gitignore
- .idea/Algorithm-Study.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- DoIt/CH01/2750.java
- DoIt/CH01/timeComplexityExample1.java
https://www.acmicpc.net/problem/2750
<br/>
> 시간복잡도를 고려하고, 병합 정렬을 사용해보는 문제
- 연산 횟수는 1초에 1억 번 연산하는 것을 기준으로 생각
- 연산 횟수 = 알고리즘 시간 복잡도 x 데이터의 크기
- 시간 복잡도 도출 기준
- 상수는 시간 복잡도 계산에서 제외
- 가장 많이 중첩된 반복문의 수행 횟수가 시간 복잡도의 기준이 됨
- 병합정렬
<br/>
.
<br/>
> [0319] 2750번 - 수 정렬하기

- DoIt/CH01/11720.java
https://www.acmicpc.net/problem/11720
<br/>
이번에는 scanner 대신에 buffer를 사용해 문제를 풀어보았다. 
소요시간에서 차이를 보였다.
<br/>
.
<br/>
> [0320] 11720 - 숫자의 합

- src/Main.java
https://www.acmicpc.net/problem/2493
<br/>
반복문을 너무 많이 사용해서 시간 초과를 너무 많이 겪어 시간 복잡도를 최대한 줄일 수 있는 방법을 찾았습니다...
처음에는 모든 숫자를 전부 스택에 저장하고 하나하나 pop을 통해 비교한 뒤 다시 스택을 채우는 식으로 코드를 작성했었는데 시간 초과가 발생해 풀이를 변경하였습니다.
문제 특성상 스택에 저장되는 숫자들이 내림차순이 아닌 경우 그 전 숫자는 사용되지 않는다는 특성을 파악해... 스택을 내림차순으로 유지할 수 있도록 코드를 수정하였습니다...!
문제를 잘 분석해서 좀 더 효율적인 아이디어를 떠올리를 연습을 해야할 거 같네요!😊
<br/>
혹시 다른 아이디어가 있다면 알려주세요...😂
<br/>
> [0320] 2493번 - 

- 1339.cpp
https://www.acmicpc.net/problem/1339
<br/>
> 알파벳에 0~9 숫자 하나씩 대입하여 덧셈 연산의 최댓값을 구하는 문제!
**첫번째 풀이**
자릿수, 빈도가 큰 순으로 9부터 0까지 수를 부여하면 되지 않을까 생각했다.
좀 복잡하지만 map 선언해서 자릿수와 빈도를 저장하고, 벡터에 옮겨준 다음에 sort 시켰다.
예제 답은 다 나왔지만…1%에서 틀려버렸다. 뭐가 문제일까??
→ 사실 빈도는 중요하지 않은거 같다. 자릿수만 고려하면 될거 같음!
**반례**
```
2
CECC
AEDCC
정답 : 106554
```
8788
97688
(내 첫번째 풀이대로 하면 위의 숫자로 나오는데 그럼 합이 최댓값이 아님)
→ 아하 E에 7을 부여했는데 8을 부여하면 세번째 자릿수 E, D를 더할때 더 큰 값이 나옴!
→ **각 알파벳이 등장하는 자릿수를 다 기록해두고, 만약 자릿수가 같다면 그 다음에 어떤 위치에 나오는지 확인해서 더 먼저 나오는 알파벳에 큰 수를 부여하면 될거 같다!!!**
<br/>
**두번째 풀이**
그런데..위에서 얻은 해결책은 구현하기 너무 어려웠다..결국 힌트를 보고 풀 수 있었다.
알파벳별로 자릿수에 해당하는 값을 더한 뒤, 가장 큰 값부터 9부터 차례로 부여하면 쉽게 해결할 수 있다.
예를 들어, 'ABCD'라면 A는 1000, B는 100, C는 10, D는 1이 된다.
'ABAD'라면 A는 1000 + 10 = 1010, B는 100, D는 1이 된다.
→ 이렇게 하면 자릿수의 크기와 빈도를 한 번에 고려할 수 있다!
<br/>
> 제가 실수로 이전 …
> [0320] 1339번 - 단어 수학

- .idea/workspace.xml
- README.md
- src/Main.java
https://www.acmicpc.net/problem/6198
<br/>
첫번째 풀이는 스택에 건물을 전부 저장하고 하나씩 pop하며 내림차순을 만들어 개수를 세려고 하는 방법이였으나... 접근 방법이 잘못되어 풀이를 제대로 하지 못했다...
두번째 풀이는 스택에 push할 때 내림차순을 유지하면서 pop을 할때마다 pop되는 객체가 내려다볼 수 있는 건물 수를 계산하는 방법이였다.
세번째 풀이는 스택 push 시 내림차순 유지하는 것은 동일하지만 pop하면서 stack  size를 통해 계산하는 방법이였다.
이 모든 과정이 틀렸다고 해 문제를 다시 읽다 발견한 내용이 각 값들의 범위였다... sum을 int가 아니고 long으로 설정해주니 두번째와 세번째 풀이가 맞았다!
-> **각 자료형의 범위를 잘 알아두고 문제를 풀 때 유념해야겠다**! 이렇게 틀린 덕분에 더 좋은 풀이를 작성해볼수 있었던 것 같다...
<br/>
<br/>
> [0321] 6198번 - 옥상 정원 꾸미기

- DoIt/CH01/11659.java
- DoIt/CH01/1546.java
https://www.acmicpc.net/problem/1546
https://www.acmicpc.net/problem/11659
<br/>
- 어제 배운대로 scanner보다는 bufferedreader를 사용해 문제를 풀고자 했다. scanner가 더 편하지만 속도가 느리다고 한다..! 
- 대신 bufferedreader는 무조건 문자열로 바꾸기 때문에 정수형이나 실수형 변수에 저장하기 위해서는 입력과 형변환을 해줘야 한다. `Double.parseDouble()`을 사용해 String형에서 double형으로 바꿔야 한다.
<br/>
> 토요일에 문제를 못 풀 것 같아서 2개 놀립니다..!
<br/>
> [0321, 0322] 1546, 11659 - 평균, 구간 합 구하기4

- .vscode/settings.json
- 1092.cpp
https://www.acmicpc.net/problem/1092
<br/>
> 크레인의 무게 제한, 박스의 무게가 주어지고 모든 박스를 움직이는데 걸리는 최소 시간을 구하는 문제!
**첫번째 풀이**
크레인의 무게 제한은 벡터에 저장해두고 내림차순 정렬해주고 박스의 무게는 우선순위 큐에 넣어주었다.
while 문을 돌면 크레인이 이동시킬 박스를 찾는데, 우선순위 큐의 top에 있는 박스부터 보고 만약 해당 박스를 들지 못 한다면 임시 벡터에 넣어준다. (해당 크레인이 들 수 있는 박스 나올때까지 우선순위 큐 돌면서 봄..)
크레인이 어떤 박스를 들었다 하면 임시 벡터의 박스를 큐에 다시 넣어주고, 다음 크레인이 움직일 박스를 찾는 로직으로 코드를 작성했다.
→ 시간초과 났다. 우선순위 큐를 사용하는게 최적이라고 생각했는데, 시간복잡도가 큰가보다…
→ 근데 생각해보니 우선순위 큐에서 계속 pop했다 push 했다 하는게 엄청 비효율적인거 같다. 그냥 벡터로 바꾸자!
**두번째 풀이**
그냥 vector에 저장해서 crane과 box를 모두 내림차순 정렬하고, 해당 crane이 옮길 수 있는 박스를 찾아서 vector에서 삭제해주는 방식으로 문제를 풀었다.
→ 또 시간초과 났다..혹시나 해서 `ios::sync_with_stdio(false);` `cin.tie(NULL);` 빠른 입출력을 추가했는데 통과했다..정말 빠른 입출력을 못 해서 시간초과가 난걸까…🥹
<br/>
> 그리디는 정말 어려워!
<br/>
> [0321] 1092번 - 배

- src/Problem10845.java
- src/Problem17298.java
https://www.acmicpc.net/problem/17298
<br/>
[첫번째 풀이]
스택 내림차순을 유지하면서 아닐 경우 오큰수를 출력하는 방식
-> 오큰수가 입력받은 순서대로 출력되지 않은 문제 발생
[두번째 풀이]
스택 내림차순을 유지하면서 배열을 사용하여 스택 순서대로 오큰수 저장 후 배열을 반복문으로 출력
<br/>
메모리를 덜 쓰고 시간 복잡도가 더 작은 방법이 있을까요??
<br/>
> [0322] 17298 - 오큰수

- src/main/java/Problem18869.java
https://www.acmicpc.net/problem/18869
<br/>
> N개의 배열 중 좌표압축(rank)한 결과가 서로 동일한 쌍의 개수를 구해야했다.
시도1: N개 배열 중 두개를 뽑아서 동일한 경우 count를 높이는 방법
-> O(N^2) x O(좌표압축)을 해야했어서 시간초과
시도2: N개 배열 각각을 좌표압축한 후 결과를 Map의 키로 저장. 그 후 중복된 키에 대해서는  value++하였음.
-> O(N) x O(좌표압축)으로 시간단축
시간 단축이 필요했던 두가지 지점
- 두 배열(우주)의 동등성 판별
: 이중 for문 vs 등수구하기(sort, binarySearch)
- 동등한 배열의 수 구하기
: 이중 for문 vs map(key:좌표압축, value: 같은 좌표압축을 가진 우주의 개수)
<br/>
<br/>
> [0323] 18869번 - 멀티버스2

- src/Problem108451.java
- src/Problem2164.java
https://www.acmicpc.net/problem/2164
<br/>
생각해보니 Queue 클래스가 있어서 그걸로 해봤습니당!~
<br/>
<br/>
> [0324] 2164번 - 카드2

- Tree/14267.cpp
https://www.acmicpc.net/problem/14267
<br/>
- 정말 생각나는대로 풀었더니 시간초과 났다.
- 칭찬을 받은 직원 노드 ~ 리프 노드까지 가는 경로는 항상 동일하니깐 매번 칭찬을 받을 때 마다 트리를 순회하는게 아니라..뭔가 dp처럼 풀면 좋을거 같은데..
- dp 처럼 풀었는데 틀렸다 왜징..
- 아니! 처음 입력받을때 같은 사람이 칭찬을 여러번 받을 수 있다는 점을 몰랐다. 
- `score[u] = w` 를 `score[u] += w` 로 바꿔주니 통과했다.
아 근데 dp라고 하기엔 조금 애매하고..누적합..?도 아니고..🧐
<br/>
<br/>
> [0324] 14267번 - 회사 문화 1

- DoIt/CH01/11660.java
- DoIt/CH01/116600.java
https://www.acmicpc.net/problem/11660
<br/>
- 질의의 개수가 100,000이므로 질의마다 합을 구하면 안되고, 구간 합 배열을 이용해야 한다.
- 2차원 구간 합 배열 D[X][Y] 정의: 원본 배열의 (0, 0)부터 (X, Y)까지의 사각형 영역 안에 있는 수의 합
<br/>
<br/>
> [0325] 11660 - 구간 합 구하기 5

- src/Problem10866.java
https://www.acmicpc.net/problem/10866
<br/>
자바의 Deque클래스를 활용해서 구현해보았습니다.
<br/>
<br/>
> [0325] 10886번 - 덱

- src/main/java/Main.java
- src/main/java/Problem12015.java
- src/main/java/Problem18869.java
https://www.acmicpc.net/problem/2467
<br/>
> 이전에 풀었던 <세 수의 합> 문제와 유사하다. 세 숫자의 조합을 모두 탐색하면 시간초과인 것처럼 마찬가지로 두 숫자의 조합을 모두 탐색하면 시간초과다.
숫자 하나는 고르고 남은 숫자는 이분탐색으로 찾으면서 해결해야한다.
목표값이 없을 때 Arrays.binarySearch()의 반환값이 (삽입될 위치+1)*(-1)이란 건 알고 있었지만 이렇게 활용될 줄은 몰랐ㄷㅏ...
<br/>
<br/>
>  [0325] 2467- 용액

- 구현/16434.cpp
https://www.acmicpc.net/problem/16434
<br/>
칸 이동하면 생명력 감소하는 것만 구현해주면 되는데..포인트는 초기 생명력을 어떻게 설정할 것인가?? 최소 ~ 최대 전부 해볼건가??
이분 탐색으로 만약 용사가 먼저 죽는다면 초기 생명력을 올려주고, 용사가 무사히 드래곤을 물리친다면..초기 생명력을 내려서 다시 시뮬레이션 돌려보았다. (최소의 생명력을 찾는 문제이기 때문에!)
이분탐색 범위를 설정하는데.. left = 1 인게 분명한데 right 값을 계속 잘 못 설정해서 틀렸다 ㅠㅠㅠ => 블로그 글 보고 제대로 설정할 수 있었다..ㅠㅠ 근데 아직도 right 값이 왜 1e18인지 이해가 되지 않는다..
<br/>
right 값이 왜 1e18 일까요...? 충분히 큰 값이라는건 알겠는데..
왜인지 정확히 모르겠습니다 ㅜㅜ.. (이분탐색 풀때 범위 설정을 잘 못 하는 편이라 아주 속상합니다)
<br/>
> [0326] 16434번 - 드래곤 앤 던전

- python/드래곤_커브.py
- 한_줄로_서기.py
https://www.acmicpc.net/problem/15685
<br/>
> 이것도 서지님 추천을 받아서 풀어본 문제!
핵심은 시작점에서 세대수 만큼 점을 리스트에 추가 하면 된다
풀이의 큰 틀은
커브를 완성시키기 위해 움직여야 하는 방향을 다 구하고
방향대로 점을 움직이며 리스트에 추가했다
방향을 구할때
돌리고 붙일때 맨 마지막 점이 처음 점이 되는게 핵심! 이 원리로
방향은 오른쪽으로 90도 돌리고 반대 방향이 된다 ((d값 +1) % 4)
순서는 거꾸로 append 했다
모든 점만 구하고 좌표가 100밖에 안되니 n^2으로 순회하면서 정사각형 찾기
난 in을 사용하고 싶어서 set으로 변환했다
(파이썬에서 set 자료형 in은 O(1))
개인적으로 구현은 예시를 적어놓고
귀납적으로 푸는게 제일 빠른 것 같다..ㅎ
<br/>
> 삼중 for문이 조금 마음에 안드네요.. 더 좋은 방법이 있을까요?.?
<br/>
> [0327] 15685번 - 드래곤 커브

- Graph/13023.cpp
https://www.acmicpc.net/problem/13023
<br/>
- 처음에는 prev와 next가 다른 노드만 방문하도록 코드를 짰다가 틀렸는데
- 생각해보니 친구 관계로 사이클을 만들 수도 있기 때문에 visited 체크로 바꿨다.
<br/>
할게 좀 많아서..쉬운 문제를 골랐는데 한번 틀려서 슬펐다 🥲
재밌는 문제 추천해주세요..
<br/>
> [0329] 13023번 - ABCDE

- src/main/java/Main.java
- src/main/java/Problem12738.java
https://www.acmicpc.net/problem/12738
<br/>
> 가장 긴 증가하는 부분수열 시리즈를 서지님이 추천해주셔서 최근 세 문제를 계속 풀고 있어요
시리즈문제1은 dp로 풀었어서 이분탐색으로 바꾸려니까 쉽지 않구만요
좀 적응이 돼서 다음엔 우선순위큐랑 묶어서 풀어야겠습니다!
<br/>
<br/>
> [0330] 12738번 - 가장 긴 증가하는 부분수열(LIS)

- 구현/8972.cpp
https://www.acmicpc.net/problem/8972
<br/>
구현 문제이기 때문에 문제에서 하라는대로만 구현해주면 된다!!
<br/>
움직인 아두이노들이 같은 자리에 위치하고 있는지 확인하는 방법
- for문 2번 돌면서 같은 인덱스를 갖는 아두이노들이 있는지 확인하고 삭제하는 식으로 했는데
- for문 2번 도는 방법 말구...다른 좋은 방법이 있을까요
<br/>
> [0401] 8972번 - 미친 아두이노

- python/N과_M_12.py
- python/서강그라운드.py
https://www.acmicpc.net/problem/14938
<br/>
> 오랜만에 다익스트라 문제!
가중치 있는 그래프는 항상 다익스트라를 떠올리는 것 같다
모든 출발지점을 기준으로
각 노드에 도착할 수 있는 최소 거리 (cost)를 구한다
구한 cost 맵을 순회하며 m보다 작다면 temp에 더해준다
출발지점마다 구한 temp값을 ans와 비교해 큰 값을 ans로
오늘은 쉬운 문제를 푸려고 N과 M 문제를 골랐는데
너무 쉬워서 양심상 2문제 풀었다ㅜ
<br/>
> 홍익그라운드는 없나요?
<br/>
> [0401] 14938번 - 서강그라운드

- .vscode/settings.json
- Greedy/1461.cpp
https://www.acmicpc.net/problem/1461
<br/>
1. 음수 좌표, 양수 좌표를 따로 벡터에 담아주고 내림차순 정렬해줬다. (멀리 떨어진 좌표 먼저 보기위해)
2. 두 벡터 다 합쳐서 제일 거리가 멀리 떨어진 좌표를 찾고 -> 이 좌표는 무조건 마지막에 방문해야함! (왔다 갔다 안해도 되니깐)
3. 2에서 찾은 좌표를 초기 dist로 설정하고 해당 좌표로 가는 중에 방문할 수 있는 좌표들은 전부 삭제해준다 (M개만큼)
4. 후에 벡터 각각 가장 큰 좌표 방문해서 좌표 * 2 만큼 dist에 더해주고, M개의 좌표 삭제해주었다 (M개 방문할 수 있으니깐)
<br/>
그리디는 정렬이 필수인듯!?
내가 정렬하는 그리디 문제만 푸는걸수도!?
<br/>
> [0402] 1461번 - 도서관

- src/main/java/Problem11286.java
- src/main/java/Problem1654.java
- src/main/java/Problem18869.java
https://www.acmicpc.net/problem/11286
<br/>
> 자바에서는 우선순위큐를 처음 써봤습니다~ 여기에도 Comparator에 구현부에 절댓값 개념을 적용하는게 핵심인 문제입니다
<br/>
<br/>
> [0402] 11286번 - 절댓값힙

- src/Problem1021.java
https://www.acmicpc.net/problem/1021
<br/>
어떻게 최소 값을 구할 수 있을지에 고민하는데 시간이 오래걸렸던 거 같다.
일단 찾고자하는 숫자로 이동하는 횟수를 temp에 저장하고 덱의 크기의 절반과 비교해 최소 이동 횟수를 계산했다.
<br/>
<br/>
> [0403] 1021번 - 회전하는 큐

- BruteForce/17484.cpp
https://www.acmicpc.net/problem/17484
<br/>
문제를 보자마자 생각난건 DP 였지만...DP로 풀기 어려울거 같아서 그냥 dfs 로 풀었다 (난 dfs/bfs를 사랑하니깐!!!)
다음 좌표를 계산해서 다음 좌표에 있는 값을 합했을때의 결과와 함께 매개변수로 넘겨주면 된다.
<br/>
무슨 문제 풀어야핳ㄹ지도 모르겠고해서 
https://www.acmicpc.net/workbook/view/8708
이 문제집에 있는 문제를 하나씩 풀어보도록 하겠습니다! 같이 풀자ㅏ,,
<br/>
> [0403] 17484번 - 진우의 달 여행 (Small)

- python/단축키_지정.py
https://www.acmicpc.net/problem/1283
<br/>
간단한 구현 문제!
공백일때 예외처리를 깜빡하면 안된다
<br/>
<br/>
> [0403] 1283번 - 단축키 지정

- src/Problem5430.java
https://www.acmicpc.net/problem/5430
<br/>
자꾸 NoSuchElement 런타임 에러가 발생해서 코드를 살펴보니 최종 결과가 빈 배열일 경우를 고려하지 못했었다...!
<br/>
깔끔하지 못한 코드 같아서 너무 많은 아쉬움이 남습니다 ㅜㅜ
<br/>
> [0404] 5430번 - AC

- Greedy/2138.cpp
https://www.acmicpc.net/problem/2138
<br/>
현재 기준 이전의 전구 상태가 output과 다르면 현재 전구를 누르고, 같으면 그냥 넘어가는 로직이다.
앞에서부터 차례대로 누르면 0~i번째 전구의 상태는 같게 만들자! 라는 생각으로 풀면 된다.
<br/>
일단 확실히 느낀건 내가 그리디 알고리즘에 약하다는 것.. 많이 좀 풀어봐야겠다.
이 문제는 전에 풀었던 <14939번 - 불 끄기> 문제와 풀이가 비슷하다.
-> https://www.acmicpc.net/workbook/view/4380 그래서 이 문제집 또한 같이 풀기로 했다
<br/>
> [0405] 2138번 - 전구와 스위치

- src/Problem4949.java
https://www.acmicpc.net/problem/4949
<br/>
yes와 no를 출력할 경우를 각각 고려해 조건문을 달아줬던 것 같습니다.
<br/>
너무 깔끔하지 못한 코드 같아 아쉬움이 많습니다. 조건문도 너무 과다하게 사용한 거 같다는 아쉬움...?이 있네요
<br/>
> [0406] 4949번 - 균형잡힌 세상

- Backtracking/12919.cpp
https://www.acmicpc.net/problem/12919
<br/>
**첫번째 풀이**
초기 문자열에 'A'를 추가하거나, 'B'를 추가한 뒤 문자열을 뒤집는 방식으로 재귀적으로 탐색하여 T를 만들 수 있는지 확인했다.
-> **시간초과**
**두번째 풀이**
예전에 유사한 문제를 풀었던 기억이 떠올랐다. 그때는 T → S 방향으로 문자열을 축소하며 해결했었기 때문에, 이번에도 같은 방식으로 접근했다.
현재 문자열의 마지막 문자가 'A'라면 'A'를 제거한 문자열을, 뒤집은 문자열의 마지막이 'B'라면 'B'를 제거한 문자열을 재귀적으로 탐색하도록 구성했다. 최종적으로 현재 문자열이 S와 같아지면 성공으로 판단한다.
-> **통과했다**
S → T 방향은 현재 문자열의 길이가 T와 같아졌을 때만 정답 여부를 판단할 수 있고, 경우의 수가 많아진다. 반면 T → S 방향은 두 가지 조건만 벗어나면 바로 실패로 판단할 수 있어, 경우의 수가 줄어들고 정답 판별이 훨씬 빠른것 같다.
<br/>
<br/>
> [0406] 12919번 - A와 B 2

- src/Problem3986.java
https://www.acmicpc.net/problem/3986
<br/>
스택을 활용
<br/>
문제를 풀면서 거의 처음 마음에 드는 코드인거 같다.
<br/>
> [0407] 3986번 - 좋은 단어

- python/나무_자르기_개선.py
- python/어두운_굴다리.py
https://www.acmicpc.net/problem/17266
<br/>
늘 이분탐색할때 경계 값이 헷갈려서 이번 기회에 정리해 봤습니다
특히 left < right 할때 등호를 넣어 줄지
경계값의 오른쪽이 답인지 왼쪽이 답인지와 같은..
upper bound, lower bound 개념이 많은데 생략하고
내입맛에 맞춘 기계적 풀이는
탈출
left + 1 < right
좌우값 수정
left = mid
right = mid
가능한 최소 정답 : right
(FFFF TTT 모양)
가능한 최대 정답 : left
(TTTT FFF 모양)
저번에 풀었던 나무 자르기 문제도 이 방법으로 개선했다!.!
이제 코테 볼때 기계적으로? 풀수 있을듯
(안통하는 경우도 있을 것 같다)
이분 탐색 문제를 쭈욱 풀어봐야겠다
<br/>
> 
<br/>
> [0407] 17266번 - 어두운 굴다리

- java/src/CH01/Number11720.java
https://www.acmicpc.net/problem/11720
<br/>
- ASCII 코드에서 같은 의미의 문자와 숫자의 코드 값 차이는 48  e.g. 문자 ‘1’의 ASCII 코드 값은 49 -> ‘1’-48 또는 ‘1’-‘0’
<br/>
입력 받을 때 항상 `BufferedReader를 써야한다고 생각했는데, Scanner를 사용하기도 하나요? 언제 어떤 걸 써야하는 지 기준이 있는지 궁금합니다!
<br/>
> [0407] 11720 - 숫자의 합

- src/Problem10799.java
https://www.acmicpc.net/problem/10799
<br/>
처음에는
readLine하고
'('이면 일단 push
')'이면 peek해서
peek한 값이 '('이면 pop하고 stack size계산해서 sum  += stack.size()
')'이면 pop 하고 sum++
를 할 계획이였는데 ')'을 push를 한 적이 없는데 어떻게 peek한 값이 '('가 아닐 수 있겠는가.....
그래서 temp를 만들어 ch의 이전 값을 변수로 저장해두고 이게 '('인지 아닌지에 따라 sum에 어떤 값을 더해줄지 판단하는 조건문으로 변경해주었다.
<br/>
다른 분들은 어떤 방식으로 푸셨는지 궁금합니다.
<br/>
> [0408] 10799번 - 쇠막대기

- Data-Structure/2075.cpp
https://www.acmicpc.net/problem/2075
<br/>
**첫번째 풀이**
아무 생각없이 다 입력받아서 정렬해도 된다고 생각했다
-> **메모리 초과!**
N이 최대 1500이라서 1500 x 1500 x 4byte....(메모리 계산을 한번도 해보지 않았는데 앞으로 메모리도 잘 생각해야겠다..)
**두번째 풀이**
위의 에러로 모든 수를 저장하고 있으면 안된다는 것을 알았다.
우리는 N번째 큰 수만 구하면 되니깐 N개까지만 저장하자!
우선순위큐의 top에 가장 작은 수가 오도록 하고, 입력받는 수가 top보다 크면 top을 지우고 입력받은 수를 넣어주어서 큐 원소 사이즈를 N개로 제한했다. 
입력을 다 받은 뒤 큐의 top을 출력하면 N번째 큰 수가 출력된다 (큰 수 N개만 저장되어 있을 것이기 때문에!)
<br/>
<br/>
> [0408] 2075번 - N번째 큰 수

- src/main/java/Problem11279.java
https://www.acmicpc.net/problem/11279
<br/>
정말 간단한 우선순위큐 문제 입니다.
(업스트림에 커밋이 push 돼서 회수 PR을 올렸고 다시 올립니다..)
<br/>
<br/>
> [0408] 11279번 - 최대힙

- src/Problem2504.java
https://www.acmicpc.net/problem/2504
<br/>
stack을 괄호를 넣는 stack과 숫자를 넣을 스택을 구분하여 문제를 풀고자 했고 ')'이나 ']'을 만날때마다 stack에서 pop을 하고 pop한 값이 어떤 값인지에 따라 구분하여 풀려고 했다.
<br/>
이번 문제의 코드는 중복되는 것도 너무 많고 복잡해 마음에 들지 않기에... 더 풀어볼 예정입니다...
<br/>
> [0410] 2504번 - 괄호의 값

- SlidingWindow/1522.cpp
https://www.acmicpc.net/problem/1522
<br/>
사실 잘 모르겠어서 힌트를 좀 봤다. 슬라이딩 윈도우 유형이었다 -> 이 알고리즘 문제는 처음 풀어보는거 같다
윈도우 안에 a 만 채우는걸 목표로 앞에서부터 확인해주면 된다.
a의 개수만큼 윈도우 사이즈를 설정하고, 시작점을 0부터 시작해서 한번 다 돌아주면 된다.
(윈도우 안에 있는 b의 개수만큼 교환해주면 된다. 이때 우리는 윈도우 안에 b의 개수가 최소가 되는 윈도우를 찾으면 된다)
투포인터와 비슷하지만 다름!
투 포인터는 첫 포인터, 마지막 포인터 사이의 크기가 유동적이지만 슬라이딩 윈도우는 크기가 고정되어있다!
<br/>
<br/>
> [0410] 1522번 - 문자열 교환

- TwoPointer/20922.cpp
https://www.acmicpc.net/problem/20922
<br/>
어제 슬라이딩 윈도우 문제를 풀어서 그런지.. 문제를 보자마자 슬라이딩 윈도우가 생각이 났는데 이 문제는 수열의 길이를 구해야 하므로 (윈도우의 크기가 고정적이지 않음) 투포인터를 이용해야겠다고 생각했다.
left, right 을 처음에 0으로 잡고 right에 해당하는 수가 지금까지 몇개 나왔는지 count 해준다.
만약 count 값이 K보다 커지면 left를 이동하여 K개 이하가 되도록 조정해준다.
<br/>
<br/>
> [0411] 20922번 - 겹치는 건 싫어

- Greedy/1138.cpp
https://www.acmicpc.net/problem/1138
<br/>
혼자 생각하기 어려웠습니다 ㅠㅠ
**풀이**
- 키가 작은 사람 먼저 ans 배열에 배치할거다.
- 자기보다 큰 사람이 n명 있다고 하면, 내가 있을 자리 왼쪽에 빈 자리가 n개 있으면 된다.
- 미리 서있던 사람들은 어쩌피 나보다 키가 작은 사람들이라 신경 쓸 필요 없고, 빈자리 개수만 세주면 된다.
<br/>
<br/>
> [0412] 1138번 - 한 줄로 서기

- 구현/1283.cpp
https://www.acmicpc.net/problem/1283
<br/>
- 일단 뛰어쓰기도 입력받아야 하므로 getline 사용!
- `cin.ignore()`로 버퍼를 지우지 않아서 틀렸습니다가 떴다…..
**새로 써본거**
`string(size_t n, char c)`
- n : 문자 개수
- c : 집어넣을 문자
→ 같은 문자 c를 n개 반복하는 문자열 만들기
`cin.ignore()`
- 입력 버퍼에 있는 문자를 무시하는 함수
```cpp
int n;
cin >> n;        // 사용자가 숫자 입력하고 Enter
getline(cin, str);     // n 숫자만 가져가고, 개행은 버퍼에 남아있는다
```
→ 이렇게 버퍼에 개행이 남아있는 상태로 getline을 호출하면 버퍼에 남아있는 개행을 읽고 바로 종료해버린다.
cin.ignore로 버퍼에 남아있는 문자를 지워주면 해결된다!
<br/>
저는 정말 어려웠습니다,,
근데 실제 코테에 이런 문제 많이 나오는듯...!?!?
(코드가 아주 복잡한거 같아서..나중에 생각 정리 좀 하고 다시 풀어보겠습니다! )
<br/>
> [0413] 1283번 - 단축키 지정

- src/main/java/Problem1389.java
https://www.acmicpc.net/problem/1389
<br/>
한 노드에서 다른 노드까지의 거리를 구하는 거에 꽃혀서 2중 for문으로 bfs를 반복하는 큰 실수를 했네요..
bfs한번이면 모든 노드와의 거리를 구할 수 있으므로 이에 맞게 다시 수정했습니다.
<br/>
<br/>
> [0413] 1389번 - 케빈 베이컨의 6단계 법칙

- java/src/CH01/Number11659.java
- java/src/CH01/Number1546.java
https://www.acmicpc.net/problem/1546
<br/>
배열에서 최댓값을 찾는 과정에서
```
double max = scores[0];
for (int i = 1; i < N; i++){
if(scores[i] > max){
max = scores[i];
}
}
```
이렇게 풀었는데 이걸 한 줄로 ```double max = Arrays.stream(scores).max().getAsDouble();``` 이렇게 풀 수 있더라구요..!
> 짧은게 뭔가 치트키같음..
<br/>
위 방법 중 어떤 방법을 선호하는 지 의견 주시면 감사하겠습니다..
<br/>
> [0415] 1546 - 평균

- SlidingWindow/21921.cpp
https://www.acmicpc.net/problem/21921
<br/>
X를 윈도우 사이즈로 해서 sum을 갱신해나가며, 최대 sum이 몇개 반복되는지 구해주면 된다.
<br/>
코테에 슬라이딩 윈도우, 누적합 문제가 생각보다 많이 나오나보다?!
<br/>
> [0416] 21921번 - 블로그

- java/src/CH01/Number1546.java
https://www.acmicpc.net/problem/11659
<br/>
- 누적합 배열의 크기가 `inputNum + 1`인 이유 
`S[j] - S[i-1]`을 예외처리 없이(`i==0`인 경우) 해결하기 위해 한 칸씩 밀려서 저장 
즉, `S[i] = S[i-1] + A[i-1]`
<br/>
<br/>
> [0416] 11659 - 구간 합 구하기 4

- python/수_이어_쓰기.py
https://www.acmicpc.net/problem/1515
<br/>
만만하게 봤는데 푸는데 너무 오래걸렸다
사실 힌트도 봤다
<br/>
실버3인데 왜이리 어렵지?!?
쉽게 푸신분 있으면 조언 해주세요 ㅜ.ㅜ
<br/>
> [0416] 1515번 - 수 이어 쓰기

- java/src/CH01/Number11660.java
https://www.acmicpc.net/problem/11660
<br/>
- 2차원 구간 합 배열 `D[X][Y] = 원본 배열의 (0, 0)부터 (X, Y)까지의 사각형 영역 안에 있는 수의 합`
`D[i][j] = D[i][j-1] + D[i-1][j] - D[i-1][j-1] + A[i][j]`
- (x1, y1)에서 (x2, y2)까지의 요소들의 합 구하기
`D[x2][y2] -D[x1-1][y2] - D[x2][y1-1] + D[x1-1][y1-1]`
<br/>
<br/>
> [0417] 11660 - 구간 합 구하기 5

- java/src/CH01/Number10986.java
https://www.acmicpc.net/problem/10986
<br/>
- (A + B) % C == ((A % C) + (B % C)) % C
- 우리가 찾고자 하는 것은 %M의 값이 0인 경우. 즉, (S[j] - S[i]) % M == 0인 경우 i+1부터 j까지의 구간합이 M으로 나누어 떨어지는 것
때문에 누적합의 원소를 M으로 나눈 나머지 값으로 업데이트하고, 그 값이 같은 것들을 찾으면 됨
<br/>
> 어려워. .
<br/>
> [0419] 10986 - 나머지 합

- src/main/java/Problem1389.java
- src/main/java/Problem1707.java
- src/main/java/Problem2617.java
https://www.acmicpc.net/problem/1707
<br/>
그래프 문제는 별다른 언급이 없다면 connected 그래프가 아닌 것도 고려를 하고 풀어야겠다.. ㅠ
그리고 edge를 인접리스트에 넣을 때 항상 `List.contains()`를 사용했었는데 이게 시간초과의 원인이 되었다
그냥 중복 되도록 집어넣거나 중복 제거가 꼭 필요하다면 Set으로 처리하는게 시간복잡도 면에서 더 낫다!
<br/>
<br/>
> [0419] 1707번 - 이분 그래프

- BinarySearch/17266.cpp
https://www.acmicpc.net/problem/17266
<br/>
처음에 가로등이 비추는 길을 확인할때 아래와 같이 범위를 잡아줬는데 이렇게 하게되면
```cpp
for(int j = max(cur - mid, 0); j <= min(cur + mid, N); j++)
```
만약 길의 길이가 10이고 가로등의 위치가 0, 9일때, 가로등의 높이가 4라면
첫번째 가로등이 0부터 4 (= 0 + 4)까지, 두번째 가로등이 5(= 9 - 4)부터 10까지 비추어 모든 길을 다 비추는 것 같지만 사실
그림처럼 4 ~ 5 구간은 어둡다…
저렇게 범위를 설정해서는 어두운 길 파악을 제대로 하지 못 한다.
→ **그래서 나는 해당 구간 어둡지 않다는 것을 구간의 왼쪽 인덱스에만 기록해두기로 했다.** 그래서 가장 마지막 구간은 visited를 해주지 않았다. (하나 인덱스 적게 기록 ! )
```cpp
for(int j = max(cur - mid, 0); j < min(cur + mid, N); j++)
```
이렇게! 해당 인덱스가 visited이면 오른쪽 한 구간이 밝은 구간이라는 의미!
위의 예시로는 하나 적게 기록해주니 3까지만 visited를 해주어 3 ~ 4까지만 밝은 구간임을 나타낸다.
<br/>
시험 끝나면 정말로 자바로 한번 풀어보겠습니다 !! 
<br/>
> [0420] 17266번 - 어두운 굴다리

- java/src/CH01/Number2018.java
https://www.acmicpc.net/problem/2018
<br/>
- 투 포인터: 시작 인덱스와 종료 인덱스를 지정해 연속된 수 표현하기
<br/>
<br/>
> [0421] 2018 - 수들의 함 5

- src/main/java/Problem11725.java
https://www.acmicpc.net/problem/11725
<br/>
트리문제는 그래프와 어떤 차이점이 있는지 앞으로 문제 풀면서 찾아봐야겠다
<br/>
<br/>
> 20250424_1일_1알골

- java/가희와_키워드.java
- python/가희와_키워드.py
https://www.acmicpc.net/problem/22233
<br/>
파이썬은 set 자료형을 사용하면 아주 쉽다
in remove등 모두 O(1)이니 부담없이 사용하면 된다
파이썬 set 자료형은 HashTable로 구현 되어 있기 때문!
좀 만만한 문제여서 처음으로 자바로도 시도해 봤다
출력시 sout 쓰면 엄청 느리다..
저번에 지민님에게 배운 BufferedWriter를 사용해 보니 실행시간이 절반
풀이는
자바에도 HashSet 자료형이 있어서 이걸 사용해 같은 방법으로 풀 수 있었고
재밌는점은
파이썬 코드
```python
if keyword in memo_keyword:
memo_keyword.remove(keyword)
```
자바 코드
```java
memo_keywords.remove(keyword);
```
파이썬은 set에 자료가 있는지 확인하고 remove 해야하는데
자바 HashSet에서는 if문으로 내부에 해당 자료가 있는지 확인을 안해줘도 에러가 나지 않는다
이유를 물어보니 그렇다고 한다
철학이 담겼다는 말이 뭔가 아름답다
파이썬이 인터프리터 언어여서 런타임에 조금 더 깐깐하게 설계했다는 말인 것 같기도??
왜 그런 것인지 여러분들의 의견이 궁금합니다
<br/>
<br/>
> [0425]  22233번 - 가희와 키워드

- src/Problem1926.java
https://www.acmicpc.net/problem/1926
<br/>
첫 BFS...
<br/>
<br/>
> [0502] 1926번 - 그림

- src/main/java/Problem13300.java
https://www.acmicpc.net/problem/13300
<br/>
꽤 오랜만에 알골을 풀어서 스트레칭처럼 가벼운 문제로 풀었습니담
<br/>
지금까지 풀은 유형별로 한사이클 더 돌리면서 유형 몇가지만 추가해서 풀어보려고합니다(그리디, 투포인터, BST, 해시)
<br/>
> [0430] 13300번 방배정

- python/랭킹전_대기열.py
https://www.acmicpc.net/problem/20006
<br/>
게임 대기열 방을 매칭 해주는 문제
+- 10 레벨 내에 사람들만 매칭해줄 수 있고
먼저 만든 방을 우선순위로 넣어 줘야 한다
풀이는 간단하지만!
딕셔너리 풀이를 고집하다가 몇 번 틀리고 리스트를 사용하는 풀이로 바꾸니 바로 풀렸다 (입력 순서를 잘못 저장한 것 같은데 고치는 것 보다 자료형 바꾸는게 낫다고 생각이 들었다)
한가지 풀이를 고집하지 말자.,.!
<br/>
<br/>
> [0430]  20006번 - 랭킹전 대기열

- C++/Graph/16988.cpp
https://www.acmicpc.net/problem/16988
<br/>
**풀이**
1. loc에 내가 놓을 수 있는 자리 저장하기
- 상하좌우에 2가 있는 0인 자리에 내가 돌을 놓을 수 있다
2. 같은 그룹의 검정 돌들은 묶어서 black 배열에 저장
3. loc 중에서 2 자리를 뽑아서 (브루트포스로) 돌을 놓고, black 배열을 돌며 각 그룹이 전부 흰돌 또는 board의 경계로 막혀있는지 확인 (= 상하좌우에 0이 없다면)
- 만약 그룹 내에 모든 돌이 위의 조건을 만족한다면 그룹 사이즈를 cnt에 더해주고 최종으로 ans와 cnt를 비교해서 정답을 갱신해주면 된다!
한번 틀렸었는데, 아래와 같은 반례가 있었다.
```
3 3
1 0 1
1 1 1
1 0 2
// answer : 1
```
나는 무조건 상하좌우에 2가 있는 위치만 loc에 저장했기 때문에 (2,1) 자리만 loc에 저장되었다.
-> loc에서 2자리를 뽑지 못 하기 때문에 제대로 된 답이 나오지 않음.
그래서 2근처에 돌 하나만 놓아도 검정돌이 죽는 경우를 따로 함수로 빼서 처리해주었다.
<br/>
오늘은 제가 좋아하는 bfs에 약간의 구현이 섞인 문제를 풀었습니다
<br/>
> [0501] 16988번 - Baaaaaaaaaduk2 (Easy)

- src/Problem2178.java
https://www.acmicpc.net/problem/2178
<br/>
<br/>
<br/>
> [0502] 2178번 - 미로 탐색

- src/Problem7576.java
https://www.acmicpc.net/problem/7576
<br/>
<br/>
<br/>
> [0504] 7576번 - 토마토

- C++/DP/2169.cpp
https://www.acmicpc.net/problem/2169
<br/>
**풀이**
- DP 문제이다.
- dp[i][j] : {i, j} 위치에 도달하기까지의 최댓값을 갱신하며 {N, M} 까지 가주면 된다.
- 최댓값을 갱신할 때, 왼쪽, 오른쪽, 위에서 온 방향만 고려해주면 된다.
- 나는 일단 (위 또는 왼쪽에서 온 경우)를 한번 다 계산해서 left 배열에 저장해주고
- (위 또는 오른쪽에서 온 경우)를 다 계산해서 right 배열에 저장해주고
- left, right의 최댓값을 dp[i][j]에 저장해주었다!
<br/>
원래 코드는
```
// 위에서 내려온 거 VS 왼쪽에서 온
dp[i][1][0] = max(dp[i - 1][1][0], dp[i - 1][1][1]) + ground[i][1];
for(int j = 2; j <= M; j++) {
dp[i][j][0] = max(dp[i - 1][j][0], dp[i - 1][j][1]) + ground[i][j];
dp[i][j][0] = max(dp[i][j][0], dp[i][j - 1][0] + ground[i][j]);
}
// 위에서 내려온 거 VS 오른쪽에서 온
dp[i][M][1] = max(dp[i - 1][M][0], dp[i - 1][M][1]) + ground[i][M];
for(int j = M - 1; j >= 1; j--) {
dp[i][j][1] = max(dp[i - 1][j][0], dp[i - …
```
> [0506] 2169번 - 로봇 조종하기

- src/main/java/Problem3015.java
https://www.acmicpc.net/problem/3015
<br/>
<br/>
오아시스 재결합이 어려웠던 만큼 굉장히 어렵네요..
<옥상정원 꾸미기>문제는 범위(a,b)에 대해서 a가 최대값이기만 하면 됐었는데 이문제는 a,b모두 그 사이 값들의 최대값 이상이어야 한다는 점이 너무 헷갈렸습니다. 오히려 간단하게 뒤를 볼 수 있는 숫자는 무엇인지, 그 때 앞을 볼 수 있는 숫자는 무엇인지 생각했었다면 더 쉽게 풀었을지도..
> 오아시스 공연 보러가고 싶습니다..
<br/>
> [0509] 3015번 - 오아시스 재결합

- C++/SlidingWindow/28339.cpp
https://www.acmicpc.net/problem/28339
<br/>
**풀이**
- 수비 위치마다 우선순위 큐를 하나씩 할당했다.
- visited[10]에 현재 윈도우 안에서 해당 수비 위치에서의 최댓값을 기록해주었다.
- 윈도우를 한칸씩 이동하며 left 위치에 있는 포지션, 능력이 visited에 기록되어 있다면 빼주고, 해당 포지션의 우선순위 큐를 보며 가방 큰 능력을 저장해주었다.
- right는 한칸 이동하면 해당 위치의 포지션, 능력을 pq에 넣어주고, pq에서 윈도우 밖으로 나간 능력이 있는지 체크해서 지워주었다.
<br/>
채연이가 추천해준 문제를..드디어 풀었습니다
어려웠다..
<br/>
> [0510] 28339번 - 이상한 드래프트

- C++/Hash/베스트앨범.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/42579
<br/>
내가 규칙만 잘 정하고..그 규칙대로만 구현한다면 쉬운 문제
**점수가 높은 n개의 원소를 출력하는 문제**가 코테에 자주 등장하는거 같은데 나만의 풀이 방법이 있다.
조건만 보면 우선순위 큐에 원소를 넣고, 큐의 top에 가장 점수가 높은 원소를 두면 될거 같지만 오히려 반대로
가장 낮은 점수의 원소를 넣으면, 항상 큐의 사이즈를 n으로 유지하고 문제를 풀 수 있다.
(큐의 사이즈가 n이고 큐의 top보다 현재 원소가 크다면, 큐의 top은 지우고 현재 원소를 대신 넣을 수 있다는 의미)
<br/>
<br/>
> [0514] 프로그래머스(고득점 Kit : 해시) - 베스트 앨범

- C++/구현/H-Index.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/42747
<br/>
벡터 사이즈 - 현재 인덱스 = 현재 위치 ~ 끝까지의 원소 개수가 나온다.
만약 현재 위치의 원소가 위에서 구한 개수보다 크거나 같으면 ans에 개수를 저장하고 끝내면 된다.
<br/>
전에 풀었을 때는....예외 처리 생각하다 결국 풀지 못 했는데
이번에 예외처리 없이 그냥 코드를 제출하니 맞았다 왜지???
만약 원소가 [1 2 3 5 6 7 8] 이면 답이 4가 되어야 하는데, 
현재 코드로는 4가 안 나오지 않나..?
<br/>
> [0516] 프로그래머스(고득점 Kit : 정렬) H-Index

- C++/Hash/완주하지못한선수.cpp
- C++/Queue/다리를지나는트럭.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/42576
https://school.programmers.co.kr/learn/courses/30/lessons/42583
<br/>
**두번째 문제 풀이**
- answer을 시간으로 생각했다.
- 현재 시간에서 트럭을 뺄지, 추가할지만 생각해주었다.
- 현재 큐의 크기가 브릿지 크기보다 작고, 현재 값을 넣었을 때 weight 보다 작은 경우 현재 값을 넣어주었다 (weight과 현재 시간을 같이 넣는다)
- 큐에서 뺄 트럭이 있는지 확인할때는 큐 front 원소가 큐에 들어온 시간 + 브릿지 크기 가 현재 시간보다 같거나 작아지는 경우가 바로 큐에서 빠질 타이밍이다.
<br/>
코테에 이런 시간 계산하는 문제를 많이 봤는데..정말 항상 어려운거 같다.
소마 코테에서 피씨방 시간 계산하는 문제가 아직도 생각나는데..비슷한 문제를 빨리 찾아서 풀고싶다
<br/>
> [0517] 프로그래머스(고득점 Kit: 해시, 큐) 완주하지 못한 선수, 다리를 지나는 트럭

- src/main/java/Problem3015.java
- src/main/java/ProblemKakaoWinterInternship2.java
- src/main/java/Problem_kakao_intern1.java
https://school.programmers.co.kr/learn/courses/30/lessons/258712
<br/>
<br/>
다시 꾸준히 풀어보자
<br/>
> [0602] 가장 많이 받은 선물

- src/main/java/Problem1919.java
- src/main/java/Problem1919_2.java
- src/main/java/ProblemKakaoWinterInternship2.java
https://school.programmers.co.kr/learn/courses/30/lessons/258711
<br/>
<br/>
개인적으로는 추가된 테스트케이스 때문에 좌표압축 해야하는건 너무하다 싶구만
<br/>
> [0606] 도넛과 막대그래프

- C++/Graph/2668.cpp
https://www.acmicpc.net/problem/2668
<br/>
만약 인덱스1에 3이 있으면, 인덱스에도 무조건 3이 있어야 된다.
꼬리잡기 하듯이 1 -> 3, 3 -> x, x -> y, y -> z 이렇게 인덱스가 가리키는 값을 다시 인덱스로 해서 따라가면 되는데
따라 가다가 처음 시작한 인덱스와 값이 같은 순간이 온다면 인덱스 집합과 값의 집합이 같다는 의미가 된다
=> 이걸 그래프 관점에서 보면 **노드가 사이클을 이룬다**는 의미이다 
=> 즉, **그래프의 모든 사이클의 수를 구하는 문제**이다
처음에는 for문을 돌며 visited 배열을 계속 초기화 시켜주는..약간의 완전탐색 비슷한 풀이로 풀었는데
인터넷 찾아보니 <DFS로 사이클 찾는 법> 이 많이 나왔고..아래 글을 참고해서 풀었다.
https://nicotina04.tistory.com/148
Edge 유형 4개 이런 것도 나오고..잘 알아두면 좋을거 같다.. 
<br/>
DFS, BFS로 항상 최단 거리 구하기, 최단 시간 구하기..이런 문제만 풀었는데
사이클 구하는 문제..처음 풀어보는 문제 유형이라 너무 재밌었다(근데 어려웠다)
<br/>
> [0613] 2668번 - 숫자고르기

- C++/Stack/1863.cpp
https://www.acmicpc.net/problem/1863
<br/>
y좌표의 짝을 찾는 느낌으로 풀었다.
스택의 top에 있는 수보다 작은 y 값이 들어오면, 스택에 있는 건물이 끝났음을 의미한다고 생각해서 cnt + 1 해줬다.
위의 pop 동작을 반복해주고 마지막으로 cnt와 남아있는 y 좌표 (스택 사이즈)를 더하면 정답이다!
<br/>
<br/>
> [0614] 1863번 - 스카이라인 쉬운거

- C++/BruteForce/1027.cpp
https://www.acmicpc.net/problem/1027
<br/>
- 처음에는 가장 큰 건물을 찾아서, 왼쪽으로 한번 오른쪽으로 한번 순회하며 기울기를 비교해주었는데..
- 가장 크고 높이가 같은 건물이 여러개 있을 때 어떻게 해야 할 지 모르겠어서 기준이 되는 건물을 for문으로 한번씩 다 바꿔주었다... (기준이 되는 건물 찾으면 기울기 측정을 위해 처음부터 끝까지 다시 다 순회해야함)
- 이렇게 했는데도 안 풀려서...구글링을 해보니 굉장히 중요한 포인트가 있었다
- 만약 A 건물에서 B건물을 볼 수 있다면 => B 건물에서도 A 건물을 볼 수 있다는 점 !! (두번할 작업을 한번의 작업으로 줄일 수 있다) 
- 기준이 되는 건물을 for문으로 바꿔주는건 같지만, 기울기 측정을 기준 건물의 오른쪽 건물들로만 측정해줬다.
- 왜냐면 이미 왼쪽에 있는 건물들이 기준 건물이었을때, 다 측정이 되었을 것이기 때문에..
- 건물 시야 확인은 기울기를 측정하면서 max 기울기보다 현재 기울기가 더 크면 시야를 확보한 것으로 판단했다
<br/>
엄청 쉬워보이는 문제였는데 3일이나 걸렸던 문제이다 .. 
<br/>
> [0618] 1027번 - 고층 건물

- src/Problem1012.java
https://www.acmicpc.net/problem/1012
<br/>
처음에는 입력 받은 것들을 바로바로 처리하면 좋을 거 같다고 생각했는데 풀이가 잘 생각이 안나서
늘 풀던 방법으로 풀어버렸다...
오늘 좋은 풀이를 공부해서 내일 다시 풀어서 다른 문제와 함께 올려보겠습니다!
<br/>
좋은 방법이 있을까요..?
<br/>
> [0619] 1012번 - 유기농 배추

- src/main/java/Main.java
- src/main/java/Problem11328.java
- src/main/java/Problem1919.java
- src/main/java/programmers/KthNumber.java
https://www.acmicpc.net/problem/11328
<br/>
두 문자열이 동일한 알파벳 종류 & 개수 인지 확인하는 문제.
<br/>
<br/>
> [0702] 11328-strfy

- src/Problem10026.java
https://www.acmicpc.net/problem/10026
<br/>
어떻게 적록색약인 경우와 아닌 경우를 함께 계산할 수 있을까...!
큐와 배열을 2개씩 사용
<br/>
<br/>
> [0702] 10026번 - 적록색약

- src/Problem5427.java
- src/Problem7562.java
https://www.acmicpc.net/problem/7562
<br/>
<br/>
<br/>
> [0614] 7562번 - 나이트의 이동

- src/Problem2583.java
https://www.acmicpc.net/problem/2583
<br/>
문제가 넓이 오름차순 출력인지 모르고... 한참을 왜 틀렸는지 고민했네요...ㅠ
<br/>
코드가 너무 지저분해요..! 어떻게 개선하면 좋을까요?
<br/>
> [0903] 2583번 - 영역 구하기

- src/Problem2468.java
https://www.acmicpc.net/problem/2468
<br/>
제 안좋은 습관 같은데 제 멋대로 특정 케이스는 안따져도 된다고 논리 없이 넘기는 경향이 있는거 같아요...
모든 케이스를 고려해서 틀리는 일을 줄여야겠어요...
<br/>
<br/>
> [0906] 2468번 - 안전 영역

- src/Problem6593.java
https://www.acmicpc.net/problem/6593
<br/>
정말 많이 틀렸는데...
1. count++ 해서... count가 증가가 안되는 문제
2. Escape가 아닌 Excape
3. 11 minute(s).가 아닌 11minute(s).
4. 한층이 채워지면 한줄이 공백이 들어가는데 그걸 고려하지 않았던 점
외에 사소한 문제들 여러개가 있었습니다...
더 꼼꼼히... 풀어야겠어요..!!
<br/>
<br/>
> [0907] 6593번 - 상범 빌딩

- Java/src/main/java/bfs/PS_87694.java
https://school.programmers.co.kr/learn/courses/30/lessons/87694
<br/>
- 테두리만 남기는 작업 고민을 많이 했다. (결국 구글링의 도움을 받았는데  이 문제가 2배 확장해서 테두리만 남기는 대표적인 문제 유형이라고 한다)
**2배 확장해야 하는 이유**
- 실제로 사각형의 테두리를 따라가는 건 오른쪽 첫번째 그림처럼 가야하지만, BFS는 오른쪽 두번째 그림처럼 가기 때문에 좌표를 다 2배 확장시켜줘서 접점을 없애버리는거다.
- 2배 확장해서 테두리만 잘 남기고, bfs 한번 더 해주면 끝!!!
- 두번째 힘들었던 점은 테두리 남기는 작업
- 처음에는 0인 칸에서 시작해서 처음으로 만나는 1만 테두리로 체크해줬더니 코너 부분은 1 마킹이 안되는거다. 그래서 bfs 돌때 대각선 이동까지 하도록 해주고 만약 대각선 이동을 하면 dist + 2를 해줬는데 .. 엣지 케이스에서 걸리는건지 62점 받았다.
- 방법을 바꿔서, (1,1)->(100,100) 다 돌면서 일단 내 위치가 1이고 내 위치 기준 상하좌우 대각선 중에 하나라도 0인 칸이 있으면 테두리로 마킹해줬다. 이러면 코너까지 마킹이 잘 되어서 뒤에는 bfs만 잘 돌아주면 된다.
<br/>
<br/>
> [0907] 프로그래머스-아이템 줍기

- Java/src/main/java/BinarySearch/PS_43238.java
https://school.programmers.co.kr/learn/courses/30/lessons/43238
<br/>
최소 시간은 1이고, 최대 시간은 times 배열에 가장 긴 시간의 n배이다. (가장 긴 시간이 걸리는 심사로 n명이 모두 들어간 경우)
이분탐색으로 mid값을 심사 시간으로 나누면 해당 시간대로 몇명의 사람을 심사할 수 있는지 나오는데 
이거의 총 합이 n명보다 커지는 최소 mid 값을 찾으면 된다!
<br/>
<br/>
> [0921] 43238번 - 입국심사
